buttonconfig = {

	# "Y_UP" : "UP" ,
	# "Y_DOWN" : "DOWN" ,
	# "Y_LEFT" : "LEFT" ,
	# "Y_RIGHT" : "RIGHT" ,
	"A" : "X" ,
	"S" : "Y" ,
	"X" : "A" ,
	"Z" : "B" ,
	"RSHIFT"  : "RT" ,
	"LSHIFT" : "LT" ,
	"RCONTROL" : "RB" ,
	"LCONTROL" : "LB" ,
	"HOME" : "START" ,
	"INSERT" : "SELECT" ,
	"Q" : "LS",
	"E" : "RS",
	"I" : "DPAD_UP",
	"K" : "DPAD_DOWN",
	"J" : "DPAD_LEFT" ,
	"L" : "DPAD_RIGHT" ,
}